services:
  clientsapi:
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ConnectionStrings__BancoDB=Server=host.docker.internal;Database=ClientsDb;User Id=sa;Password=sa;TrustServerCertificate=True;
    networks:
      - default-network

networks:
  default-network:
    driver: bridge
